### ISSUE TITLE
Link in repository description is broken

### ISSUE THREAD

**Issue by pbek** [ezsystems/LegacyBridge#109]
The link <https://doc.ez.no/display/DEVELOPER/Coming+to+eZ+Platform+from+eZ+Publish> in the repository topic doesn't work any more, <https://doc.ezplatform.com/en/1.7/migrating/migrating_from_ez_publish_platform/> would be a working link.

**Comment by emodric** [comment]
Hi Patrizio! Do you want to create a PR with the fix?

**Comment by pbek** [comment]
I would have, but I'm not aware that it is possible to create PRs for the repository description. :)

**Comment by emodric** [comment]
Ah, okay, I missed that :)

@andrerom Can you fix this then?

**Comment by andrerom** [comment]
Done, but I used latest and not 1.7 ;)
