### ISSUE TITLE
[Feature] Handle storage folder

### ISSUE THREAD

**Issue by andrerom** [ezsystems/LegacyBridge#114]
Find a way to handle storage folder, however as it should not be versioned the question is how. So might be current status Q where user needs to pick this is maybe right approach, otherwise it will need to be configurable.

**Comment by emodric** [comment]
What does it mean to handle storage folder? What needs to be handled exactly?

**Comment by andrerom** [comment]
setup symlinks for instance to somewhere safe outside legacy folder, but tbh it's rather custom thing. If you are on NFS you will most likely setup mount point somehow, and if on single server do something else.
