### ISSUE TITLE
Unable to load datatype 'ezrichtext'

### ISSUE THREAD

**Issue by ReaperSoon** [ezsystems/LegacyBridge#133]
Hi,

I installed an EzPlatform 2.0 following this page : https://www.ezplatform.com/
I created the database and install data with commands :

    $ php app/console doctrine:database:create
    $ php app/console ezplatform:install clean

After I installed LegacyBridge 2.0

Every work fine, I can access the Legacy backend.
But when I want to edit one existing class "article" class, I get this error:

    attribute 'ezrichtext': () Unable to load datatype : ezrichtext

I seems that EzPlatform replaced ezxmltext by ezrichtext. But when I install clean data with php **app/console ezplatform:install clean** it create "article" class with ezrichtext that does not exists in Legacy, right ?

So, how to not have this issue ?

Thanks

**Comment by andrerom** [comment]
@ReaperSoon Either way, install this one: https://github.com/netgen/NetgenRichTextDataTypeBundle

If you for some reason still want to install a new legacy db, then use either setupwizard or the PR here which no one cleaned up yet.

**Comment by emodric** [comment]
@andrerom Should we require the bundle in `composer.json` and add it to install instructions, just like xmltext bundle?

**Comment by andrerom** [comment]
@emodric yes, makes sense here.

**Comment by ReaperSoon** [comment]
Hi guys,

I installed this vendor, cleared the cache and check again my class "article" but i still have the error message.
However, I can now create an attribute type "richtext"

**Comment by andrerom** [comment]
@ReaperSoon as far as I know, should not really matter. but what @emodric suggests above will imply it should be installed before install step, as it will be installed during setup for legacy bridge.

**Comment by emodric** [comment]
@ReaperSoon What was missing from install instructions is that you need `ngsymfonytools` legacy extension too. Activate the extension, clear legacy caches and see if you still get the error.

I added it now to the README for future reference.

**Comment by ReaperSoon** [comment]
Good, it works fine, thanks :)

**Comment by emodric** [comment]
Rich text datatype bundle added to install docs in #143
