### ISSUE TITLE
SignalSlot not fired

### ISSUE THREAD

**Issue by ReaperSoon** [ezsystems/LegacyBridge#149]
Hi,

I try to catch the onPublish signal slot but is seems to not work with LegacyBridge.
Is there a way to catch this event in the symfony stack ? I don't want to do it in legacy stack.

Thanks

**Comment by emodric** [comment]
@ReaperSoon This is by design. Operations executed through the legacy stack do not fire new stack signals.

Unless someone contributes some way of translating legacy operations into new stack signals, the only way you can do it is through the legacy workflows, calling code from the new stack.

**Comment by andrerom** [comment]
Yes I can confirm this. New/Platform stack does not trigger legacy workflows, and legacy does not trigger new/platform stack signals.
