### ISSUE TITLE
setCurrentUserReference in eZContentObjectEditHandler not transmitted to other services

### ISSUE THREAD

**Issue by stevecohenfr** [ezsystems/LegacyBridge#154]
Hi,

I try to use symfony stack in eZContentObjectEditHandler but when I login with admin account it seems to not transmit the new user to ezpublish.api.service.content

Here is the short code

    class MyHandler extends eZContentObjectEditHandler
    {
        function publish($contentObjectID, $contentObjectVersion)
        {
            $serviceContainer = ezpKernel::instance()->getServiceContainer();
            $admin = $serviceContainer->get('ezpublish.api.service.user')->loadUser(14);
            $serviceContainer->get('ezpublish.api.repository')->getPermissionResolver()->setCurrentUserReference($admin);
            echo $serviceContainer->get('ezpublish.api.repository')->getPermissionResolver()->getCurrentUserReference()->getUserId(); // 14
            $serviceContainer->get('ezpublish.api.service.content')->loadContent($contentObjectID, null, $contentObjectVersion); // Same echo inside the loadContent function = 10 (anonymous)
        }
    }

And obviously I get the error 

> User does not have access to 'versionread' 'content' with: contentId '343', versionNo '1''

**Comment by zerustech** [comment]
@stevecohenfr It might be a bug in symfony, please refer to https://github.com/ezsystems/ezpublish-kernel/pull/2378 and symfony/symfony#27776 for details.

**Comment by andrerom** [comment]
Are you on Symfony 3.4.12?

**Comment by stevecohenfr** [comment]
@andrerom Yes I am...

**Comment by stevecohenfr** [comment]
Need I to upgrade symfony ?

**Comment by andrerom** [comment]
downgrade to 3.4.11, fix comes in 3.4.13 whenever they decide to release that.

**Comment by andrerom** [comment]
Best is to just set conflict like we do as of in 2.2:
https://github.com/ezsystems/ezplatform/blob/7eb1e21b45fffc6c1d3c3f6c5f9652b3c952a889/composer.json#L68-L71

**Comment by stevecohenfr** [comment]
I applied a patch using this pull request https://github.com/symfony/symfony/pull/27776 but maybe it's better to downgrade using the conflict in composer.json
Thanks guys
