### ISSUE TITLE
Question: Is it possible to create content via the contentService in a pre-publish triggered legacy workflow?

### ISSUE THREAD

**Issue by SalvatorePollaci** [ezsystems/LegacyBridge#168]
I'm currently using https://github.com/stevecohenfr/legacy-publish-handler-bundle to call a symfony method via a pre-published triggered Legacy Workflow(all it does is create a legacy extension with a workflow event type which calls a symfony method when triggered). In such symfony method I'm trying to create a folder content object as so:

```
// Login admin user
$this->user = $this->userService->loadUserByLogin($username);
$this->permissionResolver->setCurrentUserReference($this->user);

$contentType = $this->contentTypeService->loadContentTypeByIdentifier($contentTypeIdentifier);
$contentCreateStruct = $this->contentService->newContentCreateStruct($contentType, $locale);
$locationCreateStruct = $this->locationService->newLocationCreateStruct($parentLocationId);
$draft = $this->contentService->createContent($contentCreateStruct, [$locationCreateStruct]);
$content = $this->contentService->publishVersion($draft->versionInfo);
```

But the workflow fails as a fatal error is thrown. In particular the following happens:
- LegacyPublishVersionSlot's 'receive' method is executed which excutes eZContentOperationCollection::registerSearchObject($signal->contentId)
- eZContentOperationCollection's 'registerSearchObject' method calls eZContentObject::fetch( $objectID )
- eZContentObject's 'fetch' method executes a mysql query(found here: eZContentObject::createFetchSQLString) which returns no rows

```
SELECT ezcontentobject.*,
                               ezcontentclass.serialized_name_list as serialized_name_list,
                               ezcontentclass.identifier as contentclass_identifier,
                               ezcontentclass.is_container as is_container
                           FROM
                               ezcontentobject,
                               ezcontentclass
                           WHERE
                               ezcontentobject.id='<NEW FOLDER CONTENT ID>' AND
                               ezcontentclass.id = ezcontentobject.contentclass_id AND
                               ezcontentclass.version=0
```

The problem here is that the query returns no rows as a previously opened transaction which has no knowledge of this new content id currently present in DB is still open.
If I force to rollback such transaction(while debugging with xdebug) or I comment the 'eZContentOperationCollection::registerSearchObject($signal->contentId)' call in 'LegacyPublishVersionSlot' I don't get the fatal error.

Question: Is there any workaround to such problem, i.e. creating content via the contentService in a pre-publish triggered legacy workflow?
I really would like to avoid creating a full old-style legacy extension.

Thanks

**Comment by andrerom** [comment]
Legacy _(mysqli)_ and platform _(pdo via Doctrine dbal)_ does not share database connection, so you will never see data in transactions from one to the other.

**Comment by SalvatorePollaci** [comment]
Thank you @andrerom. As the content is correctly created and published via content service, and just the registerSearchObject method is generating a fatal error, do you reckon there is some kind of workaround(even an ugly one) I can apply to the legacy Bridge bundle(or any other part of eZ) to avoid such fatal error or someway tell eZ Publish that such content Id now exists?
Or is the only solution to create a legacy extension?
Thanks in advance.

**Comment by andrerom** [comment]
When working with workflows it's best to stay pure on legacy code as it's often within the publishing transaction, optionally some reusable library that does not depend on Platform API. 

But maybe @emodric or others might be better tips for you here.

**Comment by gggeek** [comment]
Just a FYI: the same thing which can be done using the legacy-publish-handler-bundle can also be achieved via the ezworkflowenginebundle. It might be just a tad more complex to set up, but it gives (imho) more flexibility...

**Comment by andrerom** [comment]
This is not for Q&A, so Closing this. Please use forums or slack.
