### ISSUE TITLE
[Feature] allow overtaking legacy db connection and log writer

### ISSUE THREAD

**Issue by gggeek** [ezsystems/LegacyBridge#182]
A lot of subtle issues arise from the fact that ez4 and ez5/6/7 do not share the same db connection.
What if they did?
It seems to me that it would not be too hard to implement that by way of a legacy extension which provides customized ez4 db connectors (which are just wrappers around the doctrine connection in use by ez5).

In a similar vein, it could be useful to be able to route the ez4 log writing through the sf logging configuration.
Albeit this is not easy to do in a 'clean' way, it should be possible to achieve by providing an override for eZ4 kernel class eZLog, and running the legacy autoload generation command with the appropriate allow-overrides flag.

WDYT?

**Comment by andrerom** [comment]
This package as well as legacy itself is no longer reciving new features.
