### ISSUE TITLE
dumpAssets called too early on post-install-cmd script

### ISSUE THREAD

**Issue by Simounet** [ezsystems/LegacyBridge#85]
Hi,
First of all, thanks for this hopeful repository to me! 👍 

## Use case:
- legacy bridge already set up on a Git repository
- `php composer.phar install --prefer-dist`
- `Incenteev\ParameterHandler\ScriptHandler::buildParameters` => OK
- [...]
- `Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets` => OK
- `eZ\Bundle\EzPublishCoreBundle\Composer\ScriptHandler::dumpAssets` => KO because:
`The source file "/ezroot/app/../web/extension/ezjscore/design/standard/lib/yui/3.17.2/build/yui/yui-min.js" does not exist.`

## To fix
I need to launch manually `php app/console ezpublish:legacy:assets_install --symlink`.

**Comment by emodric** [comment]
@Simounet Just move `"eZ\\Bundle\\EzPublishLegacyBundle\\Composer\\ScriptHandler::installAssets"` call before `dumpAssets`, in your `composer.json`, that should do it.

I must say I've never even thought about including legacy assets via Assetic :) I guess a note could be added to install instructions. WDYT @bdunogier @wizhippo ?

**Comment by Simounet** [comment]
Thanks Edi, I thought about this one but I get an other error:
``` php
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
> eZ\Bundle\EzPublishLegacyBundle\Composer\ScriptHandler::installLegacyBundlesExtensions
> eZ\Bundle\EzPublishLegacyBundle\Composer\ScriptHandler::generateAutoloads
Running script 'bin/php/ezpgenerateautoloads.php' in eZ Publish legacy context
PHP Warning:  require(Base/src/base.php): failed to open stream: No such file or directory in /ezroot/ezpublish_legacy/bin/php/ezpgenerateautoloads.php on line 52
PHP Fatal error:  require(): Failed opening required 'Base/src/base.php' (include_path='.:') in /ezroot/ezpublish_legacy/bin/php/ezpgenerateautoloads.php on line 52

Warning: require(Base/src/base.php): failed to open stream: No such file or directory in /ezroot/ezpublish_legacy/bin/php/ezpgenerateautoloads.php on line 52

Fatal error: require(): Failed opening required 'Base/src/base.php' (include_path='.:') in /ezroot/ezpublish_legacy/bin/php/ezpgenerateautoloads.php on line 52
Script eZ\Bundle\EzPublishLegacyBundle\Composer\ScriptHandler::generateAutoloads handling the post-install-cmd event terminated with an exception
```

And just for info, I followed [these instructions](https://github.com/ezsystems/LegacyBridge/blob/master/INSTALL.md#add-the-composer-legacy-post--scripts).

**Comment by Simounet** [comment]
I temporary fixed this on ezpublish_legacy/bin/php/ezpgenerateautoloads.php:21 but I know it is not supposed to be like this:
```php
$legacyVendorDir = getcwd() . "/../vendor";
```
Because I don't have any vendor folder into the ezpublish_legacy directory that getcwd() is pointing to.

**Comment by emodric** [comment]
@Simounet This is also described in install instructions, in section called "Configuring Symfony app folder in legacy", that should fix it.

**Comment by Simounet** [comment]
You're right but this `config.php` file is not here when I do a `composer install` and I don't have any control before post install scripts launched.

**Comment by emodric** [comment]
You need to create it by yourself, before install, it won't be overwritten or removed.

**Comment by Simounet** [comment]
Can this repository point to a version of the legacy already containing this configured file? This is what the legacybridge is for, am I correct?

**Comment by emodric** [comment]
Well, I have this prepared on my account: https://github.com/emodric/ezplatform-legacy, but it's not official.

**Comment by Simounet** [comment]
Ah ah, I did the same thing. Can we do something official?

**Comment by emodric** [comment]
As far as I know, there is talk to create a semi-official way of installing legacy bridge, when is that going to happen, I don't know.

**Comment by andrerom** [comment]
> As far as I know, there is talk to create a semi-official way of installing legacy bridge, when is that going to happen, I don't know.

check with community board, they where the once talking about doing it. I think the issue is lack of agreement on what should be done and then actually do it.

**Comment by andrerom** [comment]
@emodric is this kind of solved now? _(install doc on this repo being gradually simplified and made official)_ Or is there something missing that should be coordinated with community members?

**Comment by emodric** [comment]
@andrerom The first point, about `installAssets` which need to be placed before `dumpAssets`, remains unsolved I guess. The point about configuring the app folder is solved.
